project:
  type: book
  output-dir: docs

execute:
  freeze: auto

book:
  title: "The pmtables Book"
  subtitle: "Tables for Pharmacometrics"
  author: "Kyle Baron, Pharm.D., Ph.D."
  date: today
  date-format: medium
  repo-url: https://github.com/metrumresearchgroup/pmt-book
  repo-subdir: book
  repo-branch: main
  repo-actions: [source, issue]
  search: 
    location: navbar
    type: overlay
  chapters:
    - index.qmd
    - stable.qmd
    - panel.qmd
    - spanners.qmd
    - longtable.qmd
    - pipe.qmd
    - preview.qmd
    - sanitize.qmd
    - pmtable.qmd
  navbar: 
    background: white
    foreground: darkgrey
    right:
      - icon: globe2
        href: https://metrumrg.com


# Hex colors
# aqua 03b9b4
# blue 0082b4
format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    code-line-numbers: true
    fontsize: "15pt"
    linkcolor: "#0082b4"
    title-block-banner: "#0082b4"
    title-block-banner-color: "white"
  # pdf:
  #   documentclass: scrreprt
